Exercise
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression
SVM
Decision Tree
Random Forest

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier



In [15]:
from sklearn.datasets import load_iris
iris=load_iris()

In [16]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [18]:
from sklearn.model_selection import cross_val_score

In [17]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [47]:
l_scores=cross_val_score(LogisticRegression(solver='lbfgs',max_iter=10000), iris.data, iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [48]:
np.average(l_scores)

0.9733333333333334

In [50]:
d_scores=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [51]:
np.average(d_scores)

0.9533333333333334

In [53]:
s_scores=cross_val_score(SVC(),iris.data,iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [54]:
np.average(s_scores)

0.9666666666666666

In [55]:
r_scores=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
r_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [56]:
np.average(r_scores)

0.9533333333333334